name = input('What is you name?\n')
surname = input('What is you surname?\n')
collegeyears = input('What is you college year ?\n')
code = input('what is you code ?\n')
print('My name is :%s.' %name)
print('My surname is :%s.' %surname)
print('My college years is :%s.' %collegeyears)
print('My code is :%s.' %code)
