first = input('Input  First Number:')
second = input('Input  Second Number:')
third = input('Input   Third Number:')
fourth = input('Input  Fourth Number:')
five = input('Input  Five Number:')
printf('Float of %s Equal'%first,float(first))
printf('Complex of %s Equal'%first,Complex(first))
printf('Float of %s Equal'%first,float(second))
printf('Complex of %s Equal'%first,Complex(second))
printf('Float of %s Equal'%first,float(third))
printf('Complex of %s Equal'%first,Complex(third))
printf('Float of %s Equal'%first,float(fourth))
printf('Complex of %s Equal'%first,Complex(fourth))
printf('Float of %s Equal'%first,float(five))
printf('Complex of %s Equal'%first,Complex(five))
